version: '3.8'

services:
  backend:
    image: kareem2002k/chat-app-backend:latest  # Add image tag for Docker Hub
    build:
      context: ./chat-app-backend
    ports:
      - "5001:5001"
    env_file:
      - chat-app-backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  frontend:
    image: kareem2002k/chatapp-frontend:latest  # Add image tag for Docker Hub
    build:
      context: ./chatapp
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
