version: '3.8'

services:
  backend:
    build:
      context: ./chat-app-backend
    ports:
      - "5001:5001"
    env_file:
      - chat-app-backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./chatapp
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host
    depends_on:
      - backend

volumes:
  mongo-data:
