services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"   # Change host port to 8081
      - "50000:50000" # Agents communication with controller
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    name: jenkins_home
