pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                nodejs('node-22') {
                           sh '''
                    cd chat-app-backend
                    npm ci
                    npx jest
                    '''
                }
            }
        }

 
    }    
}