pipeline {
    agent any // Runs on any available agent

    environment {
        // Define environment variables here, if needed
        BUILD_DIR = 'build'
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the code from the repository
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                dir('../app') { // Update path to where your Dockerfile is located
                    // Change directory to where Dockerfile is located
                    echo 'Building Docker image...'
                    sh 'docker build -t my-app-image .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('../app') { // Update path to where your Dockerfile is located
                    // Change directory to where Dockerfile is located
                    echo 'Running Docker container...'
                    sh 'docker run --rm -d -p 3000:3000 my-app-image'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive build artifacts for later use
                echo 'Archiving artifacts...'
                archiveArtifacts artifacts: "${env.BUILD_DIR}/**", allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            // Actions to always run, e.g., clean up
            echo 'Cleaning up...'
            sh 'docker system prune -f' // Optional: Clean up unused Docker images and containers
        }
        success {
            // Actions to run on successful build
            echo 'Build was successful!'
        }
        failure {
            // Actions to run on failed build
            echo 'Build failed!'
        }
        unstable {
            // Actions to run if the build is unstable
            echo 'Build is unstable!'
        }
    }
}
